export interface LatexSymbol {
  command: string;   // inserted into editor
  display: string;   // rendered in the button via KaTeX
  description: string;
}

export interface SymbolCategory {
  id: string;
  name: string;
  symbols: LatexSymbol[];
}

export const SYMBOL_CATEGORIES: SymbolCategory[] = [
  {
    id: "greek-lower",
    name: "Greek (lower)",
    symbols: [
      { command: "\\alpha", display: "\\alpha", description: "\\alpha" },
      { command: "\\beta", display: "\\beta", description: "\\beta" },
      { command: "\\gamma", display: "\\gamma", description: "\\gamma" },
      { command: "\\delta", display: "\\delta", description: "\\delta" },
      { command: "\\epsilon", display: "\\epsilon", description: "\\epsilon" },
      { command: "\\varepsilon", display: "\\varepsilon", description: "\\varepsilon" },
      { command: "\\zeta", display: "\\zeta", description: "\\zeta" },
      { command: "\\eta", display: "\\eta", description: "\\eta" },
      { command: "\\theta", display: "\\theta", description: "\\theta" },
      { command: "\\vartheta", display: "\\vartheta", description: "\\vartheta" },
      { command: "\\iota", display: "\\iota", description: "\\iota" },
      { command: "\\kappa", display: "\\kappa", description: "\\kappa" },
      { command: "\\varkappa", display: "\\varkappa", description: "\\varkappa" },
      { command: "\\lambda", display: "\\lambda", description: "\\lambda" },
      { command: "\\mu", display: "\\mu", description: "\\mu" },
      { command: "\\nu", display: "\\nu", description: "\\nu" },
      { command: "\\xi", display: "\\xi", description: "\\xi" },
      { command: "\\pi", display: "\\pi", description: "\\pi" },
      { command: "\\varpi", display: "\\varpi", description: "\\varpi" },
      { command: "\\rho", display: "\\rho", description: "\\rho" },
      { command: "\\varrho", display: "\\varrho", description: "\\varrho" },
      { command: "\\sigma", display: "\\sigma", description: "\\sigma" },
      { command: "\\varsigma", display: "\\varsigma", description: "\\varsigma" },
      { command: "\\tau", display: "\\tau", description: "\\tau" },
      { command: "\\upsilon", display: "\\upsilon", description: "\\upsilon" },
      { command: "\\phi", display: "\\phi", description: "\\phi" },
      { command: "\\varphi", display: "\\varphi", description: "\\varphi" },
      { command: "\\chi", display: "\\chi", description: "\\chi" },
      { command: "\\psi", display: "\\psi", description: "\\psi" },
      { command: "\\omega", display: "\\omega", description: "\\omega" },
    ],
  },
  {
    id: "greek-upper",
    name: "Greek (upper)",
    symbols: [
      { command: "\\Gamma", display: "\\Gamma", description: "\\Gamma" },
      { command: "\\Delta", display: "\\Delta", description: "\\Delta" },
      { command: "\\Theta", display: "\\Theta", description: "\\Theta" },
      { command: "\\Lambda", display: "\\Lambda", description: "\\Lambda" },
      { command: "\\Xi", display: "\\Xi", description: "\\Xi" },
      { command: "\\Pi", display: "\\Pi", description: "\\Pi" },
      { command: "\\Sigma", display: "\\Sigma", description: "\\Sigma" },
      { command: "\\Upsilon", display: "\\Upsilon", description: "\\Upsilon" },
      { command: "\\Phi", display: "\\Phi", description: "\\Phi" },
      { command: "\\Psi", display: "\\Psi", description: "\\Psi" },
      { command: "\\Omega", display: "\\Omega", description: "\\Omega" },
      { command: "\\varGamma", display: "\\varGamma", description: "\\varGamma" },
      { command: "\\varDelta", display: "\\varDelta", description: "\\varDelta" },
      { command: "\\varTheta", display: "\\varTheta", description: "\\varTheta" },
      { command: "\\varLambda", display: "\\varLambda", description: "\\varLambda" },
      { command: "\\varXi", display: "\\varXi", description: "\\varXi" },
      { command: "\\varPi", display: "\\varPi", description: "\\varPi" },
      { command: "\\varSigma", display: "\\varSigma", description: "\\varSigma" },
      { command: "\\varUpsilon", display: "\\varUpsilon", description: "\\varUpsilon" },
      { command: "\\varPhi", display: "\\varPhi", description: "\\varPhi" },
      { command: "\\varPsi", display: "\\varPsi", description: "\\varPsi" },
      { command: "\\varOmega", display: "\\varOmega", description: "\\varOmega" },
    ],
  },
  {
    id: "operators",
    name: "Operators",
    symbols: [
      { command: "+", display: "+", description: "+" },
      { command: "-", display: "-", description: "-" },
      { command: "\\pm", display: "\\pm", description: "\\pm" },
      { command: "\\mp", display: "\\mp", description: "\\mp" },
      { command: "\\times", display: "\\times", description: "\\times" },
      { command: "\\div", display: "\\div", description: "\\div" },
      { command: "\\cdot", display: "\\cdot", description: "\\cdot" },
      { command: "\\ast", display: "\\ast", description: "\\ast" },
      { command: "\\star", display: "\\star", description: "\\star" },
      { command: "\\circ", display: "\\circ", description: "\\circ" },
      { command: "\\bullet", display: "\\bullet", description: "\\bullet" },
      { command: "\\oplus", display: "\\oplus", description: "\\oplus" },
      { command: "\\ominus", display: "\\ominus", description: "\\ominus" },
      { command: "\\otimes", display: "\\otimes", description: "\\otimes" },
      { command: "\\oslash", display: "\\oslash", description: "\\oslash" },
      { command: "\\odot", display: "\\odot", description: "\\odot" },
      { command: "\\wedge", display: "\\wedge", description: "\\wedge" },
      { command: "\\vee", display: "\\vee", description: "\\vee" },
      { command: "\\cap", display: "\\cap", description: "\\cap" },
      { command: "\\cup", display: "\\cup", description: "\\cup" },
      { command: "\\sqcap", display: "\\sqcap", description: "\\sqcap" },
      { command: "\\sqcup", display: "\\sqcup", description: "\\sqcup" },
      { command: "\\uplus", display: "\\uplus", description: "\\uplus" },
      { command: "\\setminus", display: "\\setminus", description: "\\setminus" },
      { command: "\\dagger", display: "\\dagger", description: "\\dagger" },
      { command: "\\ddagger", display: "\\ddagger", description: "\\ddagger" },
      { command: "\\amalg", display: "\\amalg", description: "\\amalg" },
      { command: "\\wr", display: "\\wr", description: "\\wr" },
      { command: "\\triangleleft", display: "\\triangleleft", description: "\\triangleleft" },
      { command: "\\triangleright", display: "\\triangleright", description: "\\triangleright" },
      { command: "\\bigtriangleup", display: "\\bigtriangleup", description: "\\bigtriangleup" },
      { command: "\\bigtriangledown", display: "\\bigtriangledown", description: "\\bigtriangledown" },
      { command: "\\bigcirc", display: "\\bigcirc", description: "\\bigcirc" },
    ],
  },
  {
    id: "relations",
    name: "Relations",
    symbols: [
      { command: "=", display: "=", description: "=" },
      { command: "\\neq", display: "\\neq", description: "\\neq" },
      { command: "<", display: "<", description: "<" },
      { command: ">", display: ">", description: ">" },
      { command: "\\leq", display: "\\leq", description: "\\leq" },
      { command: "\\geq", display: "\\geq", description: "\\geq" },
      { command: "\\leqq", display: "\\leqq", description: "\\leqq" },
      { command: "\\geqq", display: "\\geqq", description: "\\geqq" },
      { command: "\\ll", display: "\\ll", description: "\\ll" },
      { command: "\\gg", display: "\\gg", description: "\\gg" },
      { command: "\\lll", display: "\\lll", description: "\\lll" },
      { command: "\\ggg", display: "\\ggg", description: "\\ggg" },
      { command: "\\equiv", display: "\\equiv", description: "\\equiv" },
      { command: "\\sim", display: "\\sim", description: "\\sim" },
      { command: "\\simeq", display: "\\simeq", description: "\\simeq" },
      { command: "\\approx", display: "\\approx", description: "\\approx" },
      { command: "\\approxeq", display: "\\approxeq", description: "\\approxeq" },
      { command: "\\cong", display: "\\cong", description: "\\cong" },
      { command: "\\propto", display: "\\propto", description: "\\propto" },
      { command: "\\subset", display: "\\subset", description: "\\subset" },
      { command: "\\supset", display: "\\supset", description: "\\supset" },
      { command: "\\subseteq", display: "\\subseteq", description: "\\subseteq" },
      { command: "\\supseteq", display: "\\supseteq", description: "\\supseteq" },
      { command: "\\subsetneq", display: "\\subsetneq", description: "\\subsetneq" },
      { command: "\\supsetneq", display: "\\supsetneq", description: "\\supsetneq" },
      { command: "\\sqsubset", display: "\\sqsubset", description: "\\sqsubset" },
      { command: "\\sqsupset", display: "\\sqsupset", description: "\\sqsupset" },
      { command: "\\sqsubseteq", display: "\\sqsubseteq", description: "\\sqsubseteq" },
      { command: "\\sqsupseteq", display: "\\sqsupseteq", description: "\\sqsupseteq" },
      { command: "\\in", display: "\\in", description: "\\in" },
      { command: "\\notin", display: "\\notin", description: "\\notin" },
      { command: "\\ni", display: "\\ni", description: "\\ni" },
      { command: "\\perp", display: "\\perp", description: "\\perp" },
      { command: "\\parallel", display: "\\parallel", description: "\\parallel" },
      { command: "\\mid", display: "\\mid", description: "\\mid" },
      { command: "\\nmid", display: "\\nmid", description: "\\nmid" },
      { command: "\\vdash", display: "\\vdash", description: "\\vdash" },
      { command: "\\dashv", display: "\\dashv", description: "\\dashv" },
      { command: "\\models", display: "\\models", description: "\\models" },
      { command: "\\prec", display: "\\prec", description: "\\prec" },
      { command: "\\succ", display: "\\succ", description: "\\succ" },
      { command: "\\preceq", display: "\\preceq", description: "\\preceq" },
      { command: "\\succeq", display: "\\succeq", description: "\\succeq" },
      { command: "\\asymp", display: "\\asymp", description: "\\asymp" },
      { command: "\\bowtie", display: "\\bowtie", description: "\\bowtie" },
      { command: "\\smile", display: "\\smile", description: "\\smile" },
      { command: "\\frown", display: "\\frown", description: "\\frown" },
      { command: "\\doteq", display: "\\doteq", description: "\\doteq" },
    ],
  },
  {
    id: "arrows",
    name: "Arrows",
    symbols: [
      { command: "\\to", display: "\\to", description: "\\to" },
      { command: "\\gets", display: "\\gets", description: "\\gets" },
      { command: "\\leftarrow", display: "\\leftarrow", description: "\\leftarrow" },
      { command: "\\rightarrow", display: "\\rightarrow", description: "\\rightarrow" },
      { command: "\\leftrightarrow", display: "\\leftrightarrow", description: "\\leftrightarrow" },
      { command: "\\Leftarrow", display: "\\Leftarrow", description: "\\Leftarrow" },
      { command: "\\Rightarrow", display: "\\Rightarrow", description: "\\Rightarrow" },
      { command: "\\Leftrightarrow", display: "\\Leftrightarrow", description: "\\Leftrightarrow" },
      { command: "\\iff", display: "\\iff", description: "\\iff" },
      { command: "\\implies", display: "\\implies", description: "\\implies" },
      { command: "\\uparrow", display: "\\uparrow", description: "\\uparrow" },
      { command: "\\downarrow", display: "\\downarrow", description: "\\downarrow" },
      { command: "\\updownarrow", display: "\\updownarrow", description: "\\updownarrow" },
      { command: "\\Uparrow", display: "\\Uparrow", description: "\\Uparrow" },
      { command: "\\Downarrow", display: "\\Downarrow", description: "\\Downarrow" },
      { command: "\\Updownarrow", display: "\\Updownarrow", description: "\\Updownarrow" },
      { command: "\\nearrow", display: "\\nearrow", description: "\\nearrow" },
      { command: "\\nwarrow", display: "\\nwarrow", description: "\\nwarrow" },
      { command: "\\searrow", display: "\\searrow", description: "\\searrow" },
      { command: "\\swarrow", display: "\\swarrow", description: "\\swarrow" },
      { command: "\\mapsto", display: "\\mapsto", description: "\\mapsto" },
      { command: "\\longmapsto", display: "\\longmapsto", description: "\\longmapsto" },
      { command: "\\hookleftarrow", display: "\\hookleftarrow", description: "\\hookleftarrow" },
      { command: "\\hookrightarrow", display: "\\hookrightarrow", description: "\\hookrightarrow" },
      { command: "\\leftharpoonup", display: "\\leftharpoonup", description: "\\leftharpoonup" },
      { command: "\\leftharpoondown", display: "\\leftharpoondown", description: "\\leftharpoondown" },
      { command: "\\rightharpoonup", display: "\\rightharpoonup", description: "\\rightharpoonup" },
      { command: "\\rightharpoondown", display: "\\rightharpoondown", description: "\\rightharpoondown" },
      { command: "\\rightleftharpoons", display: "\\rightleftharpoons", description: "\\rightleftharpoons" },
      { command: "\\longleftarrow", display: "\\longleftarrow", description: "\\longleftarrow" },
      { command: "\\longrightarrow", display: "\\longrightarrow", description: "\\longrightarrow" },
      { command: "\\longleftrightarrow", display: "\\longleftrightarrow", description: "\\longleftrightarrow" },
      { command: "\\Longleftarrow", display: "\\Longleftarrow", description: "\\Longleftarrow" },
      { command: "\\Longrightarrow", display: "\\Longrightarrow", description: "\\Longrightarrow" },
      { command: "\\Longleftrightarrow", display: "\\Longleftrightarrow", description: "\\Longleftrightarrow" },
      { command: "\\leadsto", display: "\\leadsto", description: "\\leadsto" },
    ],
  },
  {
    id: "bigops",
    name: "Big Ops",
    symbols: [
      { command: "\\sum", display: "\\sum", description: "\\sum" },
      { command: "\\prod", display: "\\prod", description: "\\prod" },
      { command: "\\coprod", display: "\\coprod", description: "\\coprod" },
      { command: "\\int", display: "\\int", description: "\\int" },
      { command: "\\iint", display: "\\iint", description: "\\iint" },
      { command: "\\iiint", display: "\\iiint", description: "\\iiint" },
      { command: "\\oint", display: "\\oint", description: "\\oint" },
      { command: "\\oiint", display: "\\oiint", description: "\\oiint" },
      { command: "\\oiiint", display: "\\oiiint", description: "\\oiiint" },
      { command: "\\bigcup", display: "\\bigcup", description: "\\bigcup" },
      { command: "\\bigcap", display: "\\bigcap", description: "\\bigcap" },
      { command: "\\bigsqcup", display: "\\bigsqcup", description: "\\bigsqcup" },
      { command: "\\bigvee", display: "\\bigvee", description: "\\bigvee" },
      { command: "\\bigwedge", display: "\\bigwedge", description: "\\bigwedge" },
      { command: "\\bigoplus", display: "\\bigoplus", description: "\\bigoplus" },
      { command: "\\bigotimes", display: "\\bigotimes", description: "\\bigotimes" },
      { command: "\\bigodot", display: "\\bigodot", description: "\\bigodot" },
      { command: "\\biguplus", display: "\\biguplus", description: "\\biguplus" },
    ],
  },
  {
    id: "delimiters",
    name: "Delimiters",
    symbols: [
      { command: "(", display: "(", description: "(" },
      { command: ")", display: ")", description: ")" },
      { command: "[", display: "[", description: "[" },
      { command: "]", display: "]", description: "]" },
      { command: "\\{", display: "\\{", description: "\\{" },
      { command: "\\}", display: "\\}", description: "\\}" },
      { command: "\\langle", display: "\\langle", description: "\\langle" },
      { command: "\\rangle", display: "\\rangle", description: "\\rangle" },
      { command: "|", display: "|", description: "|" },
      { command: "\\|", display: "\\|", description: "\\|" },
      { command: "\\lfloor", display: "\\lfloor", description: "\\lfloor" },
      { command: "\\rfloor", display: "\\rfloor", description: "\\rfloor" },
      { command: "\\lceil", display: "\\lceil", description: "\\lceil" },
      { command: "\\rceil", display: "\\rceil", description: "\\rceil" },
      { command: "\\lvert", display: "\\lvert", description: "\\lvert" },
      { command: "\\rvert", display: "\\rvert", description: "\\rvert" },
      { command: "\\lVert", display: "\\lVert", description: "\\lVert" },
      { command: "\\rVert", display: "\\rVert", description: "\\rVert" },
      { command: "\\backslash", display: "\\backslash", description: "\\backslash" },
      { command: "\\left( \\right)", display: "\\left( x \\right)", description: "\\left( \\right) — auto-size" },
      { command: "\\left[ \\right]", display: "\\left[ x \\right]", description: "\\left[ \\right] — auto-size" },
      { command: "\\left\\{ \\right\\}", display: "\\left\\{ x \\right\\}", description: "\\left\\{ \\right\\} — auto-size" },
      { command: "\\left| \\right|", display: "\\left| x \\right|", description: "\\left| \\right| — auto-size" },
      { command: "\\left\\| \\right\\|", display: "\\left\\| x \\right\\|", description: "\\left\\| \\right\\| — auto-size" },
    ],
  },
  {
    id: "functions",
    name: "Functions",
    symbols: [
      { command: "\\sin", display: "\\sin", description: "\\sin" },
      { command: "\\cos", display: "\\cos", description: "\\cos" },
      { command: "\\tan", display: "\\tan", description: "\\tan" },
      { command: "\\cot", display: "\\cot", description: "\\cot" },
      { command: "\\sec", display: "\\sec", description: "\\sec" },
      { command: "\\csc", display: "\\csc", description: "\\csc" },
      { command: "\\arcsin", display: "\\arcsin", description: "\\arcsin" },
      { command: "\\arccos", display: "\\arccos", description: "\\arccos" },
      { command: "\\arctan", display: "\\arctan", description: "\\arctan" },
      { command: "\\sinh", display: "\\sinh", description: "\\sinh" },
      { command: "\\cosh", display: "\\cosh", description: "\\cosh" },
      { command: "\\tanh", display: "\\tanh", description: "\\tanh" },
      { command: "\\coth", display: "\\coth", description: "\\coth" },
      { command: "\\exp", display: "\\exp", description: "\\exp" },
      { command: "\\log", display: "\\log", description: "\\log" },
      { command: "\\ln", display: "\\ln", description: "\\ln" },
      { command: "\\det", display: "\\det", description: "\\det" },
      { command: "\\lim", display: "\\lim", description: "\\lim" },
      { command: "\\limsup", display: "\\limsup", description: "\\limsup" },
      { command: "\\liminf", display: "\\liminf", description: "\\liminf" },
      { command: "\\sup", display: "\\sup", description: "\\sup" },
      { command: "\\inf", display: "\\inf", description: "\\inf" },
      { command: "\\max", display: "\\max", description: "\\max" },
      { command: "\\min", display: "\\min", description: "\\min" },
      { command: "\\gcd", display: "\\gcd", description: "\\gcd" },
      { command: "\\operatorname{lcm}", display: "\\operatorname{lcm}", description: "\\operatorname{lcm}" },
      { command: "\\dim", display: "\\dim", description: "\\dim" },
      { command: "\\ker", display: "\\ker", description: "\\ker" },
      { command: "\\deg", display: "\\deg", description: "\\deg" },
      { command: "\\arg", display: "\\arg", description: "\\arg" },
      { command: "\\hom", display: "\\hom", description: "\\hom" },
      { command: "\\Pr", display: "\\Pr", description: "\\Pr" },
    ],
  },
  {
    id: "calculus",
    name: "Calculus",
    symbols: [
      { command: "\\partial", display: "\\partial", description: "\\partial" },
      { command: "\\nabla", display: "\\nabla", description: "\\nabla" },
      { command: "\\infty", display: "\\infty", description: "\\infty" },
      { command: "\\prime", display: "\\prime", description: "\\prime" },
      { command: "\\backprime", display: "\\backprime", description: "\\backprime" },
      { command: "\\hbar", display: "\\hbar", description: "\\hbar" },
      { command: "\\imath", display: "\\imath", description: "\\imath" },
      { command: "\\jmath", display: "\\jmath", description: "\\jmath" },
      { command: "\\ell", display: "\\ell", description: "\\ell" },
      { command: "\\Re", display: "\\Re", description: "\\Re" },
      { command: "\\Im", display: "\\Im", description: "\\Im" },
      { command: "\\wp", display: "\\wp", description: "\\wp" },
      { command: "\\aleph", display: "\\aleph", description: "\\aleph" },
      { command: "\\beth", display: "\\beth", description: "\\beth" },
      { command: "\\gimel", display: "\\gimel", description: "\\gimel" },
      { command: "\\daleth", display: "\\daleth", description: "\\daleth" },
    ],
  },
  {
    id: "logic",
    name: "Logic & Sets",
    symbols: [
      { command: "\\forall", display: "\\forall", description: "\\forall" },
      { command: "\\exists", display: "\\exists", description: "\\exists" },
      { command: "\\nexists", display: "\\nexists", description: "\\nexists" },
      { command: "\\emptyset", display: "\\emptyset", description: "\\emptyset" },
      { command: "\\varnothing", display: "\\varnothing", description: "\\varnothing" },
      { command: "\\neg", display: "\\neg", description: "\\neg" },
      { command: "\\land", display: "\\land", description: "\\land" },
      { command: "\\lor", display: "\\lor", description: "\\lor" },
      { command: "\\top", display: "\\top", description: "\\top" },
      { command: "\\bot", display: "\\bot", description: "\\bot" },
      { command: "\\therefore", display: "\\therefore", description: "\\therefore" },
      { command: "\\because", display: "\\because", description: "\\because" },
      { command: "\\mathbb{N}", display: "\\mathbb{N}", description: "Natural numbers \\mathbb{N}" },
      { command: "\\mathbb{Z}", display: "\\mathbb{Z}", description: "Integers \\mathbb{Z}" },
      { command: "\\mathbb{Q}", display: "\\mathbb{Q}", description: "Rationals \\mathbb{Q}" },
      { command: "\\mathbb{R}", display: "\\mathbb{R}", description: "Reals \\mathbb{R}" },
      { command: "\\mathbb{C}", display: "\\mathbb{C}", description: "Complex \\mathbb{C}" },
      { command: "\\mathbb{P}", display: "\\mathbb{P}", description: "Primes \\mathbb{P}" },
    ],
  },
  {
    id: "constructs",
    name: "Constructs",
    symbols: [
      { command: "\\frac{}{}", display: "\\frac{a}{b}", description: "\\frac{}{} — fraction" },
      { command: "\\sqrt{}", display: "\\sqrt{x}", description: "\\sqrt{} — square root" },
      { command: "\\sqrt[]{}", display: "\\sqrt[n]{x}", description: "\\sqrt[]{} — nth root" },
      { command: "^{}", display: "x^{n}", description: "^{} — superscript" },
      { command: "_{}", display: "x_{n}", description: "_{} — subscript" },
      { command: "^{}_{}", display: "x^{m}_{n}", description: "^{}_{} — super+subscript" },
      { command: "\\sum_{}^{}", display: "\\sum_{i=0}^{n}", description: "\\sum_{}^{} — sum with limits" },
      { command: "\\int_{}^{}", display: "\\int_{a}^{b}", description: "\\int_{}^{} — integral with limits" },
      { command: "\\lim_{}", display: "\\lim_{n \\to \\infty}", description: "\\lim_{} — limit" },
      { command: "\\frac{d}{dx}", display: "\\frac{d}{dx}", description: "\\frac{d}{dx} — derivative" },
      { command: "\\frac{\\partial}{\\partial x}", display: "\\frac{\\partial}{\\partial x}", description: "partial derivative" },
      { command: "\\binom{}{}", display: "\\binom{n}{k}", description: "\\binom{}{} — binomial" },
      { command: "\\overline{}", display: "\\overline{x}", description: "\\overline{}" },
      { command: "\\underline{}", display: "\\underline{x}", description: "\\underline{}" },
      { command: "\\overbrace{}", display: "\\overbrace{xyz}", description: "\\overbrace{}" },
      { command: "\\underbrace{}", display: "\\underbrace{xyz}", description: "\\underbrace{}" },
      { command: "\\text{}", display: "\\text{abc}", description: "\\text{} — text in math" },
      { command: "\\mathbf{}", display: "\\mathbf{x}", description: "\\mathbf{} — bold" },
      { command: "\\mathbb{}", display: "\\mathbb{R}", description: "\\mathbb{} — blackboard bold" },
      { command: "\\mathcal{}", display: "\\mathcal{L}", description: "\\mathcal{} — calligraphic" },
      { command: "\\mathfrak{}", display: "\\mathfrak{g}", description: "\\mathfrak{} — fraktur" },
      { command: "\\mathrm{}", display: "\\mathrm{x}", description: "\\mathrm{} — roman" },
      { command: "\\mathit{}", display: "\\mathit{x}", description: "\\mathit{} — italic" },
      { command: "\\mathsf{}", display: "\\mathsf{x}", description: "\\mathsf{} — sans-serif" },
      { command: "\\mathtt{}", display: "\\mathtt{x}", description: "\\mathtt{} — typewriter" },
      { command: "\\begin{pmatrix} & \\\\\\\\ & \\end{pmatrix}", display: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}", description: "pmatrix — parenthesized matrix" },
      { command: "\\begin{bmatrix} & \\\\\\\\ & \\end{bmatrix}", display: "\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}", description: "bmatrix — bracketed matrix" },
      { command: "\\begin{vmatrix} & \\\\\\\\ & \\end{vmatrix}", display: "\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}", description: "vmatrix — determinant" },
      { command: "\\begin{cases} \\\\\\\\ \\end{cases}", display: "\\begin{cases} a & \\text{if } x>0 \\\\ b & \\text{otherwise} \\end{cases}", description: "cases — piecewise" },
    ],
  },
  {
    id: "accents",
    name: "Accents",
    symbols: [
      { command: "\\hat{}", display: "\\hat{x}", description: "\\hat{}" },
      { command: "\\check{}", display: "\\check{x}", description: "\\check{}" },
      { command: "\\tilde{}", display: "\\tilde{x}", description: "\\tilde{}" },
      { command: "\\acute{}", display: "\\acute{x}", description: "\\acute{}" },
      { command: "\\grave{}", display: "\\grave{x}", description: "\\grave{}" },
      { command: "\\dot{}", display: "\\dot{x}", description: "\\dot{}" },
      { command: "\\ddot{}", display: "\\ddot{x}", description: "\\ddot{}" },
      { command: "\\dddot{}", display: "\\dddot{x}", description: "\\dddot{}" },
      { command: "\\breve{}", display: "\\breve{x}", description: "\\breve{}" },
      { command: "\\bar{}", display: "\\bar{x}", description: "\\bar{}" },
      { command: "\\vec{}", display: "\\vec{x}", description: "\\vec{}" },
      { command: "\\widehat{}", display: "\\widehat{xy}", description: "\\widehat{}" },
      { command: "\\widetilde{}", display: "\\widetilde{xy}", description: "\\widetilde{}" },
      { command: "\\overleftarrow{}", display: "\\overleftarrow{AB}", description: "\\overleftarrow{}" },
      { command: "\\overrightarrow{}", display: "\\overrightarrow{AB}", description: "\\overrightarrow{}" },
      { command: "\\overleftrightarrow{}", display: "\\overleftrightarrow{AB}", description: "\\overleftrightarrow{}" },
    ],
  },
  {
    id: "dots",
    name: "Dots & Spacing",
    symbols: [
      { command: "\\ldots", display: "a\\ldots b", description: "\\ldots — baseline dots" },
      { command: "\\cdots", display: "a\\cdots b", description: "\\cdots — centered dots" },
      { command: "\\vdots", display: "\\vdots", description: "\\vdots — vertical dots" },
      { command: "\\ddots", display: "\\ddots", description: "\\ddots — diagonal dots" },
      { command: "\\cdot", display: "a \\cdot b", description: "\\cdot — center dot" },
      { command: "\\!", display: "a{\\!}b", description: "\\! — negative thin space" },
      { command: "\\,", display: "a{\\,}b", description: "\\, — thin space" },
      { command: "\\:", display: "a{\\:}b", description: "\\: — medium space" },
      { command: "\\;", display: "a{\\;}b", description: "\\; — thick space" },
      { command: "\\ ", display: "a{\\ }b", description: "\\ — space" },
      { command: "\\quad", display: "a{\\quad}b", description: "\\quad" },
      { command: "\\qquad", display: "a{\\qquad}b", description: "\\qquad" },
      { command: "\\phantom{}", display: "a\\phantom{x}b", description: "\\phantom{}" },
    ],
  },
  {
    id: "misc",
    name: "Misc",
    symbols: [
      { command: "\\angle", display: "\\angle", description: "\\angle" },
      { command: "\\measuredangle", display: "\\measuredangle", description: "\\measuredangle" },
      { command: "\\sphericalangle", display: "\\sphericalangle", description: "\\sphericalangle" },
      { command: "\\triangle", display: "\\triangle", description: "\\triangle" },
      { command: "\\square", display: "\\square", description: "\\square" },
      { command: "\\diamond", display: "\\diamond", description: "\\diamond" },
      { command: "\\lozenge", display: "\\lozenge", description: "\\lozenge" },
      { command: "\\surd", display: "\\surd", description: "\\surd" },
      { command: "\\checkmark", display: "\\checkmark", description: "\\checkmark" },
      { command: "\\circledast", display: "\\circledast", description: "\\circledast" },
      { command: "\\circledcirc", display: "\\circledcirc", description: "\\circledcirc" },
      { command: "\\circleddash", display: "\\circleddash", description: "\\circleddash" },
      { command: "\\clubsuit", display: "\\clubsuit", description: "\\clubsuit" },
      { command: "\\diamondsuit", display: "\\diamondsuit", description: "\\diamondsuit" },
      { command: "\\heartsuit", display: "\\heartsuit", description: "\\heartsuit" },
      { command: "\\spadesuit", display: "\\spadesuit", description: "\\spadesuit" },
      { command: "\\flat", display: "\\flat", description: "\\flat" },
      { command: "\\natural", display: "\\natural", description: "\\natural" },
      { command: "\\sharp", display: "\\sharp", description: "\\sharp" },
      { command: "\\S", display: "\\S", description: "\\S — section" },
      { command: "\\P", display: "\\P", description: "\\P — paragraph" },
      { command: "\\infty", display: "\\infty", description: "\\infty" },
      { command: "\\degree", display: "90{\\degree}", description: "\\degree" },
      { command: "\\mho", display: "\\mho", description: "\\mho" },
      { command: "\\eth", display: "\\eth", description: "\\eth" },
      { command: "\\hslash", display: "\\hslash", description: "\\hslash" },
      { command: "\\complement", display: "\\complement", description: "\\complement" },
    ],
  },
];
